UHF-5007 CKEditor Language selector
City-of-Helsinki/drupal-hdbt-admin pull request #123
Opened 2022-04-01 05:53 UTC by khalima

# CKEditor Language selector [UHF-5007](https://helsinkisolutionoffice.atlassian.net/browse/UHF-5007)

A better UX language selector plugin for the CKEditor.

## What was done
* Updated webpack configuration to match with HDBT theme
* Added language selector plugin for the CKEditor and styles for the dialog

## How to install
* Make sure your instance is up and running on latest dev branch.
    * `git pull origin dev`
    * `make fresh`
* Update the HDBT Admin theme
    * `composer require drupal/hdbt_admin:dev-UHF-5007_ckeditor_language_selector && composer require drupal/helfi_platform_config:dev-UHF-5007_ckeditor_language_selector`
* Run `make drush-cr drush-updb`

## How to test
* Go to edit any page with CKEditor
* In CKEditor
   * Write a few paragraphs of text and add a phrase in some different language
   * Select the different language part of text and click on the Language selector button
   ![image](https://user-images.githubusercontent.com/1712902/161201773-e7645f75-8d35-4893-9881-60492ce6345b.png)
   * Select a language from the dropdown and click ok.
   * The selected part of text should now be in your chosen language
   * Check: https://user-images.githubusercontent.com/1712902/161203000-50706ead-7cd6-41e8-92a5-fb37e2006611.mov
* Save the node (or entity) and check that the translated texts have `<span lang="" dir=""></span>` tags.

## Other PRs
*

2022-04-01 06:04 UTC, tuutti requested changes

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +
Missing `declare(strict_types = 1)`;

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +  public function getButtons() {
Missing return type

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +  public function getFile() {
Missing return type

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +  public function isInternal() {
Missing return type

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +  public function getDependencies(Editor $editor) {
Missing return type

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +  public function getLibraries(Editor $editor) {
Missing return type

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/LanguageSelector.php
> +  public function getConfig(Editor $editor) {
Missing return type

2022-04-01 06:04 UTC, tuutti commented on modules/hdbt_admin_editorial/src/Plugin/CKEditorPlugin/QuoteCKEditorButton.php
>    public function getFile() {
Missing return type

2022-04-01 07:17 UTC, tuutti approved these changes
Approving PHP changes

2022-04-04 06:52 UTC, Arkkimaagi approved these changes
Works as described, tested with VoiceOver on iOS, works there too. 🚀

2022-04-04 11:30 UTC, merged